services:
  frontend:
    build:
      context: ./frontend
    restart: always
  backend:
    container_name: ecolab-backend
    depends_on:
      - redis
      - database
    build: backend
    command: bash runserver.sh
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "database"
      REDIS_HOST: "redis"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    restart: always
  redis:
    image: redis:alpine
    container_name: ecolab-redis
    restart: always
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "db-storage:/var/lib/postgresql/data:rw"
    restart: always
  caddy:
    image: caddy:latest
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./robots.txt:/static/robots.txt
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    restart: always
volumes:
  db-storage:
  caddy_data:
  caddy_config:
